### PR TITLE
Do not limit PyYAML version

### LINKED ISSUE #64: Error installing PyYAML during setup-python@v4 step
https://github.com/linux-system-roles/kernel_settings/actions/runs/5590666395/jobs/10220681606
```python-traceback
+ python -m pip install 'PyYAML>5,<6' --disable-pip-version-check --user
Collecting PyYAML<6,>5
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 4.5 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      /tmp/pip-build-env-kdyhx5qx/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
...
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
        File "/tmp/pip-build-env-kdyhx5qx/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-kdyhx5qx/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by felixfontein**
Fixes #64.

### CODE REVIEW

**Comment by jpmat296** [comment]
All CI sanity test based on this action are failing. Please merge this fix.

**Comment by felixfontein** [comment]
@webknjaz ping, this is rather urgent!

**Comment by webknjaz** [comment]
Ah, sorry, I'm at EuroPython and didn't see this. Best ping me on Matrix in urgent cases..

**Comment by webknjaz** [comment]
I'll update the commit message to have something useful instead of the random text and then, I'll merge.

**Comment by webknjaz** [comment]
https://github.com/ansible-community/ansible-test-gh-action/releases/tag/v1.14.1

**Pull request merged**
